### ISSUE TITLE
小晨旭

### ISSUE THREAD

**Issue by penjay** [essensoft/paylink#113]
services.Configure(Configuration.GetSection("WeChatPay"));

请问如何配置支持多种支付渠道，
如果WeChatPay中AppId配置的小程序的AppId，则小程序、PC扫码支付都没有问题。但是微信内浏览器因为需要走公众号支付，就会出错，因为微信内的openid和WechatPay中的appid是没有关联关系的

**Comment by penjay** [comment]
services.Configure<WeChatPayOptions>(Configuration.GetSection("WeChatPay"));

请问如何配置支持多种支付渠道，
如果WeChatPay中AppId配置的小程序的AppId，则小程序、PC扫码支付都没有问题。但是微信内浏览器因为需要走公众号支付，就会出错，因为微信内的openid和WechatPay中的appid是没有关联关系的

**Comment by roc916** [comment]
我想你应该补习一下 [ASP.NET Core 中的选项模式](https://docs.microsoft.com/zh-cn/aspnet/core/fundamentals/configuration/options?view=aspnetcore-5.0#named-options-support-using-iconfigurenamedoptions)
