### ISSUE TITLE
不是吧，大佬，Issues的问题都没解决啊，就关闭了吗

### ISSUE THREAD

**Issue by quqi-beep** [essensoft/paylink#116]

**Comment by roc916** [comment]
没有你说的这个通知 麻烦你看看文档再来提Issues

**Comment by quqi-beep** [comment]
我看的源码，难道看错了？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "essensoft/paylink"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月11日(星期五) 晚上6:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [essensoft/paylink] 不是吧，大佬，Issues的问题都没解决啊，就关闭了吗 (#116)





 
没有你说的这个通知 麻烦你看看文档再来提Issues

**Comment by roc916** [comment]
源码里有支付宝退款通知？你别看着微信支付，去理解支付宝好不好？
