### ISSUE TITLE
当面付-扫码支付报错

### ISSUE THREAD

**Issue by quqi-beep** [essensoft/paylink#117]
![image](https://user-images.githubusercontent.com/59988881/122007135-375fd200-cdea-11eb-8b01-6a55c4ea5424.png)
请问作者，我用电脑网站支付就可以正常生成链接，但是用当面付-扫码支付，他提示如图所示的错误，请问是证书的原因吗，如果是证书的原因，那电脑网站支付也不应该成功啊，费解，求指定一下

**Comment by roc916** [comment]
你怕是连产品权限都没开吧

**Comment by quqi-beep** [comment]
> 你怕是连产品权限都没开吧

是的，查看了一下，的确没有开通当面付的功能，多谢
