### ISSUE TITLE
调用IOptions<WeChatPayOptions> _optionsAccessor时报错

### ISSUE THREAD

**Issue by 1523400779** [essensoft/paylink#118]
配置文件中，如果设置了MchID， 在调用IOptions<WeChatPayOptions> _optionsAccessor时， 会报错：
Value = '((Microsoft.Extensions.Options.OptionsManager<Essensoft.Paylink.WeChatPay.WeChatPayOptions>)_optionsAccessor).Value' threw an exception of type 'System.Reflection.TargetInvocationException'。
这个问题发生在我升级项目至.net 5之后， 使用的paylink版本为：4.0.4
![image](https://user-images.githubusercontent.com/67778929/123554063-ed46fb00-d7b0-11eb-8e88-60143617f4f6.png)

**Comment by roc916** [comment]
请提供一个可复现此问题的项目实例.

**Comment by 1523400779** [comment]
> 请提供一个可复现此问题的项目实例.
项目比较庞大，比较难提供代码，或可以约时间远程为你演示一下?

**Comment by Ccoli** [comment]
老哥能告知下是咋解决的嘛

**Comment by xj728** [comment]
我也发生了这个问题
