### ISSUE TITLE
用你们官方的WebApplicationSample项目测试， 发现同样问题， _optionAccessor.Value报错！

### ISSUE THREAD

**Issue by 1523400779** [essensoft/paylink#119]
您好， 刚刚从github上下你们的源码， 然后用WebApplicationSample测试，发现昨天提交同样的问题， 只要在appsetting.json中添加了MchId, 如： 1000000000， 进入到WeChatPayV3Controller中的PubPay, 就会报错，如下图：
![image](https://user-images.githubusercontent.com/67778929/123596833-39cc1e00-d825-11eb-8c83-f13fa401f7fd.png)
下面是配置文件
![image](https://user-images.githubusercontent.com/67778929/123596974-5f592780-d825-11eb-8169-55293183204c.png)

**Comment by roc916** [comment]
![image](https://user-images.githubusercontent.com/12685126/123597993-9d0a8000-d826-11eb-8637-70ec7dccca20.png)


那应该是你环境问题了吧，换台机子再试试吧。

**Comment by 1523400779** [comment]
我因为发布到阿里云上报错，才在本地测试发生同样的问题。 请问你测的时候， appsettings.json里面赋值了吗？

**Comment by 1523400779** [comment]
因为我尝试把MchId设为""，就不会报同样的错误， 很奇怪

**Comment by roc916** [comment]
![image](https://user-images.githubusercontent.com/12685126/123599847-9e3cac80-d828-11eb-8afc-c6f1f39624a0.png)

**Comment by 1523400779** [comment]
![image](https://user-images.githubusercontent.com/67778929/123600205-04c1ca80-d829-11eb-9d06-14e4d1eed01b.png)
这个是我去掉配置文件中的MchId, 就不会报错.... 我找找看问题出在哪里吧， 有发现再跟你说
