### ISSUE TITLE
微信支付V2中签名类型不一致问题

### ISSUE THREAD

**Issue by henu5972** [essensoft/paylink#128]
微信支付使用 HMAC-SHA256  签名方式时，由于定义的 枚举变量名称不一致，导致请求提示  **PARAM_ERROR:sign_type**

### 代码位置
每个请求 PrimaryHandler  中 sign_type 字段

  /// <summary>
  /// 签名类型
  /// </summary>
  public enum WeChatPaySignType
  {
      MD5 = 0,
      HMAC_SHA256 = 1,
  }

`sortedTxtParams.Add(WeChatPayConsts.sign_type, signType.ToString());`

**Comment by roc916** [comment]
已修复 https://github.com/essensoft/paylink/commit/b8b1771691680fafac4363683e97a244da400557
