### ISSUE TITLE
下载账单返回的response.result.body为包含多条账单记录的string类型，也可以直接使用File.writeAllText(待生成的CSV文件路径，返回的body)将body转换为CSV格式的文件吗？

### ISSUE THREAD

**Issue by beyondjsj** [essensoft/paylink#178]
下载账单返回的response.result.body为string类型数据，包含了多条账单记录，也可以直接使用File.writeAllText(待生成的CSV文件路径，返回的body)将body转换为CSV格式的文件吗？

**Comment by roc916** [comment]
#176 #177 已经说的很清楚了。它本来就是CSV内容，即逗号分隔文本数据。至于保存至磁盘命名为xx.csv。还是直接解析保存至数据库，均可，请不要再重复询问了。
