### ISSUE TITLE
微信支付 V3接口

### ISSUE THREAD

**Issue by roc916** [essensoft/paylink#73]
[开发者文档-商户平台](https://pay.weixin.qq.com/wiki/doc/apiv3/index.shtml)
[开发者文档-服务商平台](https://pay.weixin.qq.com/wiki/doc/apiv3_partner/index.shtml)

**Comment by Essensoft-Roc** [comment]
关联 #52 #62

**Comment by LGinC** [comment]
微信支付可真行,退款相关接口的v3还在紧张开发中2333333333333
强行v3混搭v2,就像中出了个叛徒,逼死强迫症

**Comment by roc916** [comment]
> 微信支付可真行,退款相关接口的v3还在紧张开发中2333333333333
> 
> 强行v3混搭v2,就像中出了个叛徒,逼死强迫症

是的，笑死个人
